### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by AndresAlbornozgil** [fsfgroup8/OUTlets#72]
# Form

## User Story
 AS A "bored out of my mind" user
I WANT a website that can help me find local events/activities based on what I enjoy doing
SO THAT I CAN have fun and not spend hours figuring out what to do

## Aceptance Criteria
GIVEN an event/activity finder web application
WHEN I scroll down the landing page
THEN I am presented with a form that will ask me to input city & events/activities to find

**Comment by 0-Sunny-0** [comment]
Form was created and pushed in separate branch
